# syntax=docker/dockerfile:1.7
# Multi-stage Dockerfile for queFluya (Next.js 16 + Prisma + Supabase).
# Produces a small production image using Next.js standalone output.

ARG NODE_VERSION=20-alpine

# ─── Stage 1: install deps ──────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

# libc6-compat is required by some Node native modules on Alpine.
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# ─── Stage 2: build ─────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS builder
WORKDIR /app

# NEXT_PUBLIC_* env vars are baked into the client bundle at build time, so
# they must be available now (not only at runtime).
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate the Prisma client into node_modules before building, otherwise
# `import { PrismaClient } from "@prisma/client"` will fail during `next build`.
RUN npx prisma generate

RUN npm run build

# ─── Stage 3: runtime ───────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Run as an unprivileged user.
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by Next.js standalone output and bundles the
# Node.js server plus only the deps the app actually imports.
CMD ["node", "server.js"]
