/**
 * Turn the typed topic content in content/topics/ into a seed SQL file.
 *
 *   npm run build:topics
 *
 * Emits supabase/topics_seed.generated.sql (upserts by slug, so re-running and
 * re-applying is safe). Validates structure first and refuses to emit on error.
 * Apply the output with:
 *   npx prisma db execute --file supabase/topics_seed.generated.sql --schema prisma/schema.prisma
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { TOPIC_PAIRS } from '../content/topics/index'
import { buildSections, type AuthoredSide } from '../content/topics/types'
import type { Language } from '../lib/topics'

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'topics_seed.generated.sql')

type Row = {
  side: AuthoredSide
  language: Language
  level: string
  position: number
  pairKey: string
}

function collectRows(): Row[] {
  const rows: Row[] = []
  for (const pair of TOPIC_PAIRS) {
    rows.push({ side: pair.en, language: 'EN', level: pair.level, position: pair.position, pairKey: pair.pairKey })
    rows.push({ side: pair.es, language: 'ES', level: pair.level, position: pair.position, pairKey: pair.pairKey })
  }
  return rows
}

function validate(rows: Row[]): string[] {
  const errors: string[] = []
  const slugs = new Set<string>()
  for (const { side, pairKey } of rows) {
    if (slugs.has(side.slug)) errors.push(`duplicate slug: ${side.slug}`)
    slugs.add(side.slug)
    if (!side.title.trim()) errors.push(`${side.slug}: empty title`)
    if (!side.description.trim()) errors.push(`${side.slug}: empty description`)
    if (!pairKey.trim()) errors.push(`${side.slug}: empty pairKey`)
    if (!side.freeRecordingPrompt.trim()) errors.push(`${side.slug}: empty freeRecordingPrompt`)
    if (side.studySections.length === 0) errors.push(`${side.slug}: no study sections`)
    side.studySections.forEach((s, i) => {
      const where = `${side.slug} study[${i}]`
      if (!s.title.trim()) errors.push(`${where}: empty title`)
      if (s.vocabulary.length === 0) errors.push(`${where}: no vocabulary`)
      if (s.dialogue.length === 0) errors.push(`${where}: no dialogue`)
      if (s.practicePhrases.length === 0) errors.push(`${where}: no practice phrases`)
    })
  }
  return errors
}

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`

function rowValues(r: Row): string {
  const content = JSON.stringify({ sections: buildSections(r.side) })
  return [
    sqlStr(r.side.slug),
    sqlStr(r.side.title),
    sqlStr(r.side.description),
    sqlStr(r.language),
    sqlStr(r.level),
    String(r.position),
    sqlStr(r.pairKey),
    `$topic$${content}$topic$::jsonb`,
  ].join(', ')
}

function main() {
  const rows = collectRows()
  const errors = validate(rows)
  if (errors.length > 0) {
    console.error('✗ Topic validation failed:')
    for (const e of errors) console.error('  - ' + e)
    process.exit(1)
  }

  const values = rows.map((r) => `  (${rowValues(r)})`).join(',\n')
  const sql = `-- GENERATED by scripts/build-topics.ts — DO NOT EDIT BY HAND.
-- Source of truth: content/topics/. Regenerate with \`npm run build:topics\`.
-- Apply: npx prisma db execute --file supabase/topics_seed.generated.sql --schema prisma/schema.prisma

insert into public.topics (slug, title, description, language, level, position, pair_key, content)
values
${values}
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  language = excluded.language,
  level = excluded.level,
  position = excluded.position,
  pair_key = excluded.pair_key,
  content = excluded.content;
`

  writeFileSync(OUT, sql)
  console.log(`✓ Wrote ${rows.length} topics (${TOPIC_PAIRS.length} pairs) → supabase/topics_seed.generated.sql`)
}

main()
